# Generated by Django 2.2.6 on 2021-06-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20210628_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='series_date',
            field=models.IntegerField(),
        ),
    ]
